package com.phzc.profile.web.dto;

import java.io.Serializable;

public class TsContractInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.CONTRACT_ID
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private Integer contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.CONTRACT_NO
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.CONTRACT_TYPE
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private String contractType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.CONTRACT_NAME
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private String contractName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.CONTRACT_PATH
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private String contractPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.CONTRACT_SING
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private String contractSing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.PRODUCT_ID
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.ORDER_ID
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.CUST_ID
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private String custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.REMARK
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.EFFECT_TIME
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private String effectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.VALID_STATUS
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private String validStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_contract_info.INSERT_TIME
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    private String insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.CONTRACT_ID
     *
     * @return the value of ts_contract_info.CONTRACT_ID
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.CONTRACT_ID
     *
     * @param contractId the value for ts_contract_info.CONTRACT_ID
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.CONTRACT_NO
     *
     * @return the value of ts_contract_info.CONTRACT_NO
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.CONTRACT_NO
     *
     * @param contractNo the value for ts_contract_info.CONTRACT_NO
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo == null ? null : contractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.CONTRACT_TYPE
     *
     * @return the value of ts_contract_info.CONTRACT_TYPE
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public String getContractType() {
        return contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.CONTRACT_TYPE
     *
     * @param contractType the value for ts_contract_info.CONTRACT_TYPE
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setContractType(String contractType) {
        this.contractType = contractType == null ? null : contractType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.CONTRACT_NAME
     *
     * @return the value of ts_contract_info.CONTRACT_NAME
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.CONTRACT_NAME
     *
     * @param contractName the value for ts_contract_info.CONTRACT_NAME
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setContractName(String contractName) {
        this.contractName = contractName == null ? null : contractName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.CONTRACT_PATH
     *
     * @return the value of ts_contract_info.CONTRACT_PATH
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public String getContractPath() {
        return contractPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.CONTRACT_PATH
     *
     * @param contractPath the value for ts_contract_info.CONTRACT_PATH
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setContractPath(String contractPath) {
        this.contractPath = contractPath == null ? null : contractPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.CONTRACT_SING
     *
     * @return the value of ts_contract_info.CONTRACT_SING
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public String getContractSing() {
        return contractSing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.CONTRACT_SING
     *
     * @param contractSing the value for ts_contract_info.CONTRACT_SING
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setContractSing(String contractSing) {
        this.contractSing = contractSing == null ? null : contractSing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.PRODUCT_ID
     *
     * @return the value of ts_contract_info.PRODUCT_ID
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.PRODUCT_ID
     *
     * @param productId the value for ts_contract_info.PRODUCT_ID
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.ORDER_ID
     *
     * @return the value of ts_contract_info.ORDER_ID
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.ORDER_ID
     *
     * @param orderId the value for ts_contract_info.ORDER_ID
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.CUST_ID
     *
     * @return the value of ts_contract_info.CUST_ID
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.CUST_ID
     *
     * @param custId the value for ts_contract_info.CUST_ID
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.REMARK
     *
     * @return the value of ts_contract_info.REMARK
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.REMARK
     *
     * @param remark the value for ts_contract_info.REMARK
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.EFFECT_TIME
     *
     * @return the value of ts_contract_info.EFFECT_TIME
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public String getEffectTime() {
        return effectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.EFFECT_TIME
     *
     * @param effectTime the value for ts_contract_info.EFFECT_TIME
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setEffectTime(String effectTime) {
        this.effectTime = effectTime == null ? null : effectTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.VALID_STATUS
     *
     * @return the value of ts_contract_info.VALID_STATUS
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public String getValidStatus() {
        return validStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.VALID_STATUS
     *
     * @param validStatus the value for ts_contract_info.VALID_STATUS
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setValidStatus(String validStatus) {
        this.validStatus = validStatus == null ? null : validStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.UPDATE_TIME
     *
     * @return the value of ts_contract_info.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.UPDATE_TIME
     *
     * @param updateTime the value for ts_contract_info.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_contract_info.INSERT_TIME
     *
     * @return the value of ts_contract_info.INSERT_TIME
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public String getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_contract_info.INSERT_TIME
     *
     * @param insertTime the value for ts_contract_info.INSERT_TIME
     *
     * @mbggenerated Mon Aug 10 18:45:00 CST 2015
     */
    public void setInsertTime(String insertTime) {
        this.insertTime = insertTime == null ? null : insertTime.trim();
    }
}